# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
# CSDP needs lapack and blas
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install liblapack-dev libblas-dev;
    fi
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="JuMP", rev="master"))'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="PolyJuMP", rev="master"))'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="SumOfSquares", rev="master"))'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SwitchOnSafety")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SwitchOnSafety")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
