# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
# CSDP needs lapack and blas
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install liblapack-dev libblas-dev;
    fi
before_script:
  - julia -e 'Pkg.clone("git://github.com/blegat/MultivariatePolynomials.jl.git")'
  - julia -e 'Pkg.clone("git://github.com/blegat/DynamicPolynomials.jl.git")'
  - julia -e 'Pkg.clone("git://github.com/JuliaOpt/PolyJuMP.jl.git")'
  - julia -e 'Pkg.clone("git://github.com/JuliaOpt/SumOfSquares.jl.git")'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SwitchOnSafety"); Pkg.test("SwitchOnSafety"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SwitchOnSafety")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SwitchOnSafety")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
